/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GamesPlankedRouteImport } from './routes/games.planked'
import { Route as GamesTheLastCupOfChaiRouteImport } from './routes/games.the-last-cup-of-chai'
import { Route as GamesWordCrossRouteImport } from './routes/games.word-cross'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPlankedRoute = GamesPlankedRouteImport.update({
  id: '/games/planked',
  path: '/games/planked',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTheLastCupOfChaiRoute = GamesTheLastCupOfChaiRouteImport.update({
  id: '/games/the-last-cup-of-chai',
  path: '/games/the-last-cup-of-chai',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesWordCrossRoute = GamesWordCrossRouteImport.update({
  id: '/games/word-cross',
  path: '/games/word-cross',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/games/planked': typeof GamesPlankedRoute
  '/games/the-last-cup-of-chai': typeof GamesTheLastCupOfChaiRoute
  '/games/word-cross': typeof GamesWordCrossRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/games/planked': typeof GamesPlankedRoute
  '/games/the-last-cup-of-chai': typeof GamesTheLastCupOfChaiRoute
  '/games/word-cross': typeof GamesWordCrossRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/terms': typeof TermsRoute
  '/games/planked': typeof GamesPlankedRoute
  '/games/the-last-cup-of-chai': typeof GamesTheLastCupOfChaiRoute
  '/games/word-cross': typeof GamesWordCrossRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/games/planked'
    | '/games/the-last-cup-of-chai'
    | '/games/word-cross'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/games/planked'
    | '/games/the-last-cup-of-chai'
    | '/games/word-cross'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/privacy'
    | '/refunds'
    | '/terms'
    | '/games/planked'
    | '/games/the-last-cup-of-chai'
    | '/games/word-cross'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  TermsRoute: typeof TermsRoute
  GamesPlankedRoute: typeof GamesPlankedRoute
  GamesTheLastCupOfChaiRoute: typeof GamesTheLastCupOfChaiRoute
  GamesWordCrossRoute: typeof GamesWordCrossRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/planked': {
      id: '/games/planked'
      path: '/games/planked'
      fullPath: '/games/planked'
      preLoaderRoute: typeof GamesPlankedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/the-last-cup-of-chai': {
      id: '/games/the-last-cup-of-chai'
      path: '/games/the-last-cup-of-chai'
      fullPath: '/games/the-last-cup-of-chai'
      preLoaderRoute: typeof GamesTheLastCupOfChaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/word-cross': {
      id: '/games/word-cross'
      path: '/games/word-cross'
      fullPath: '/games/word-cross'
      preLoaderRoute: typeof GamesWordCrossRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  TermsRoute: TermsRoute,
  GamesPlankedRoute: GamesPlankedRoute,
  GamesTheLastCupOfChaiRoute: GamesTheLastCupOfChaiRoute,
  GamesWordCrossRoute: GamesWordCrossRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
